## data
query_data_path: data/processed/queries.mmap
pos_doc_data_path: data/processed/pos_docs.mmap
neg_doc_data_path: data/processed/neg_docs.mmap


## model
similarity_metric: l2
dim: 128
query_max_len: 32
doc_max_len: 180
mask_punctuation: true


## training
base_model: bert-base-uncased
per_device_train_batch_size: 32
weight_decay: 0.0
lr: 3.0e-06
max_train_steps: 400000
seed: 12345
gradient_accumulation_steps: 1
val_check_interval: 4000
fp16: true